"""feature flags

Revision ID: f42e9cae533c
Revises: 99a3e021d6b4
Create Date: 2026-09-16 18:17:49.523096
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f42e9cae533c'
down_revision: str | None = '99a3e021d6b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('for_students', sa.Boolean(), nullable=False),
    sa.Column('for_teachers', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
