"""solution uploads

Revision ID: 6eb85a22782c
Revises: f42e9cae533c
Create Date: 2026-09-16 18:57:02.082354
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6eb85a22782c'
down_revision: str | None = 'f42e9cae533c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'problem_id', 'user_id', name='uq_solution_per_problem')
    )
    with op.batch_alter_table('solution_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solution_uploads_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solution_uploads_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        # На существующих заданиях файл не требуется: без server_default
        # SQLite не сможет добавить NOT NULL-колонку к непустой таблице.
        batch_op.add_column(
            sa.Column(
                'requires_solution', sa.Boolean(), nullable=False,
                server_default=sa.text('0'),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('requires_solution')

    with op.batch_alter_table('solution_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solution_uploads_user_id'))
        batch_op.drop_index(batch_op.f('ix_solution_uploads_assignment_id'))

    op.drop_table('solution_uploads')
    # ### end Alembic commands ###
