"""group favorites

Revision ID: 222dcda9b194
Revises: 6eb85a22782c
Create Date: 2026-09-18 11:54:02.935952
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '222dcda9b194'
down_revision: str | None = '6eb85a22782c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_group_favorite')
    )
    with op.batch_alter_table('group_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_favorites_user_id'))

    op.drop_table('group_favorites')
    # ### end Alembic commands ###
