"""submission code

Revision ID: d2873dff92b3
Revises: 222dcda9b194
Create Date: 2026-09-18 12:47:13.623248
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd2873dff92b3'
down_revision: str | None = '222dcda9b194'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('code_fetched_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('code_fetched_at')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
